name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to 'main' if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to latest version

      - name: List repository contents  # Add this for debugging
        run: ls -R

      - name: Move website files
        run: |
          mkdir -p docs  # Create the docs directory if it doesn't exist
          mv dist/* docs/  # Move all files from the website folder to docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Set the directory to publish
